const fs = require("fs");
const path = require("path");
const { glob } = require("glob");

/**
 * Generates route imports for Vercel compatibility.
 * This script discovers all routes.ts files in modules and creates
 * explicit require() calls that work with CommonJS.
 */
async function generateRoutes() {
  const modulesDir = path.resolve(__dirname, "../src/modules");
  const outputFile = path.resolve(__dirname, "../src/routes.ts");

  console.log("🔍 Discovering route files...");

  // Find all routes.ts files in modules
  const routeFiles = await glob("**/routes.ts", {
    cwd: modulesDir,
    absolute: false,
  });

  if (routeFiles.length === 0) {
    console.warn("⚠️  No route files found in modules directory");
    return;
  }

  console.log(`📋 Found ${routeFiles.length} route file(s):`);
  routeFiles.forEach((f) => console.log(`   - modules/${f}`));

  // Generate require() statements with explicit string literals
  // This is important for bundlers to statically analyze the imports
  const imports = routeFiles
    .map((file) => {
      // Convert path to module import path
      // e.g., "general/routes.ts" -> "@/modules/general/routes"
      const importPath = `@/modules/${file.replace(/\\/g, "/").replace(".ts", "")}`;
      return `  require("${importPath}");`;
    })
    .join("\n");

  // Generate the routes.ts file content
  const content = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by: scripts/generate-routes.js
 * 
 * This file imports all route modules for Vercel compatibility.
 * The imports use explicit string literals so bundlers can statically analyze them.
 * 
 * To add new routes, create a routes.ts file in your module folder and run:
 * yarn generate-routes (or npm run generate-routes)
 */

/**
 * Imports all route modules synchronously.
 * Uses require() with explicit paths for static analysis and CommonJS compatibility.
 */
export function importRoutes(): void {
${imports}
}
`;

  // Write the generated file
  fs.writeFileSync(outputFile, content, "utf-8");
  console.log(`✅ Generated ${outputFile}`);
}

generateRoutes().catch((error) => {
  console.error("❌ Failed to generate routes:", error);
  process.exit(1);
});
