/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by: scripts/generate-routes.js
 * 
 * This file imports all route modules for Vercel compatibility.
 * The imports use explicit string literals so bundlers can statically analyze them.
 * 
 * To add new routes, create a routes.ts file in your module folder and run:
 * yarn generate-routes (or npm run generate-routes)
 */

/**
 * Imports all route modules synchronously.
 * Uses require() with explicit paths for static analysis and CommonJS compatibility.
 */
export function importRoutes(): void {
  require("@/modules/user/routes");
  require("@/modules/general/routes");
  require("@/modules/file-uploads/routes");
}
